### ISSUE TITLE
"Cannot resume the upload, original file was not found" errors when upload video

### ISSUE THREAD

**Issue by ADovgiy** [kaltura/kaltura-parallel-upload-resumablejs#1]
Almost every time, when I upload files with default setup (Simultaneous uploads: 5 Chunk size (kb): 1024) I receive this error, in response, for some chunks:
{
code: UPLOAD_TOKEN_CANNOT_RESUME
message: Cannot resume the upload, original file was not found
objectType: KalturaAPIException
args: []
}
And this error for last chunk:
{
“code”:“UPLOAD_TOKEN_CANNOT_MATCH_EXPECTED_SIZE”,
“message”:“Failed to match expected file size”,
“objectType”:“KalturaAPIException”,
“args”:[]
}
As result file did not uploaded correctly. And when I try to add mediaEntry I receive this error:
{
“code”: “UPLOAD_TOKEN_INVALID_STATUS_FOR_ADD_ENTRY”,
“message”: “Upload token is in an invalid status for adding entry, maybe the a file was not uploaded or the token was used”,
“objectType”: “KalturaAPIException”,
“args”: []
}
When I make get request for UploadToken I get status 1 for uploadtoken which means PARTIAL_UPLOAD.

Steps to reproduce:
1. Open page with plugin
2. Open dev panel in browesr in network tab 
3. Insert valid Kaltura Session key
4. Select file
5. View responses in network panel

**Comment by kaltura-hooks** [comment]
Hi @ADovgiy,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by ADovgiy** [comment]
1. Platform Windows 7 SP1, browsers Firefox, Chrome latest, anyway I don't think that this is platform relative issue
2. Using Kaltura SaaS

**Comment by jessp01** [comment]
Hi @ADovgiy,

I am able to reproduce that, albeit, intermittently.
Will look into it and keep you posted.

Thanks for reporting,

**Comment by jessp01** [comment]
Hi @ADovgiy,

Please checkout the 'dev' branch or downalod https://github.com/kaltura/kaltura-parallel-upload-resumablejs/archive/dev.zip and let me know how it went.
I tested it quite extensively against both SaaS and self hosted ENVs and it seems to work correctly now.
For a list of changes see:
https://github.com/kaltura/kaltura-parallel-upload-resumablejs/commit/340f56ac87e507a181cce49bba2a6ce8cf6efa47

Thanks,

**Comment by jessp01** [comment]
@ADovgiy - did you get a chance to try? Thanks,

**Comment by ADovgiy** [comment]
@jessp01 HI, yes I made few tests on example version, it works fine without any errors.
Thank you for fixing issue

**Comment by jessp01** [comment]
Hi @ADovgiy,

Great, thanks for confirming. Closing the issue.

**Comment by roeycohen** [comment]
this doesn't work.
seems like Kaltura is expecting for chunk #1 to arrive first, but that's not always the case.
