### ISSUE TITLE
Uploading 1 byte of data taking so much time.

### ISSUE THREAD

**Issue by Arpit1596** [kaltura/kaltura-parallel-upload-resumablejs#4]
When uploading chunks simultaneouly using this code https://github.com/kaltura/kaltura-chunked-upload-test 

The first request which is made i.e to upload a single byte from stream takes lot of time and whenever it gets uploaded it shows that it uploaded full file .
![Screenshot from 2020-04-10 19-53-23](https://user-images.githubusercontent.com/56026129/78997859-05f3d280-7b65-11ea-908d-48802812ee9c.png)

for even bigger files upto 1gb it takes time equivalent to loading rest of full file

**Comment by kaltura-hooks** [comment]
Hi @Arpit1596,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by Arpit1596** [comment]
We are using kaltura Saas and KalturaApiClient-15.14.0.jar

**Comment by jessp01** [comment]
Hello @Arpit1596 ,

I must confess that I am confused. You've written:
> When uploading chunks simultaneouly using this code https://github.com/kaltura/kaltura-chunked-upload-test

That project has nothing at all to do with this one. If you're only using it, please open an issue on that repo. When doing so, please attach the full log while masking sensitive data (entry IDs, KS strings, etc).

If you've tried using this project and had issues, please reopen this issue and elaborate.

Thank you,
